import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,mkdtemp,writeFile,readFile,rmdir,readdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{previousDirectory,rememberDirectory}=require('../dist/directoryHistory.js');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');await mkdir(path.join(root,'build'),{recursive:true});
const base=await mkdtemp(path.join(root,'build','directory-history-unit-'));
const data=path.join(base,'data'),media=path.join(base,'media'),shots=path.join(base,'shots');for(const directory of [data,media,shots])await mkdir(directory);
const file=path.join(data,'avhub-directory-choices.json');
assert.equal(await previousDirectory(data,'media'),undefined);
await rememberDirectory(data,'media',media);await rememberDirectory(data,'screenshots',shots);
assert.equal(await previousDirectory(data,'media'),media);assert.equal(await previousDirectory(data,'screenshots'),shots);
const before=await readFile(file,'utf8');const nonDirectory=path.join(base,'not-a-directory');await writeFile(nonDirectory,'keep');
await rememberDirectory(data,'media',nonDirectory);assert.equal(await readFile(file,'utf8'),before);
await rmdir(media);assert.equal(await previousDirectory(data,'media'),undefined);assert.equal(await previousDirectory(data,'screenshots'),shots);
await writeFile(file,'broken JSON');assert.equal(await previousDirectory(data,'screenshots'),undefined);
await rememberDirectory(data,'screenshots',shots);assert.equal(await previousDirectory(data,'screenshots'),shots);
await writeFile(file,JSON.stringify({version:1,folders:{media:nonDirectory,screenshots:'relative/path'}}));
assert.equal(await previousDirectory(data,'media'),undefined);assert.equal(await previousDirectory(data,'screenshots'),undefined);
assert.ok(!(await readdir(data)).some(name=>name.endsWith('.tmp')));
await rememberDirectory(path.join(base,'missing-profile'),'media',shots);
console.log(JSON.stringify({passed:true,report:base,checks:['purpose isolation','durable reload','file/missing/invalid path rejection','corruption recovery','atomic write cleanup','optional write failure does not block selection']}));
